In [1]:
from sklearn.datasets import load_iris

asignamos el dataset en un objeto, similar a un diccionario contiene keys y values

In [3]:
iris_dataset = load_iris()

DESCR es una descripcion del dataset

In [6]:
print(iris_dataset["DESCR"])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [7]:
print(iris_dataset["target_names"])

['setosa' 'versicolor' 'virginica']


los datos estan contenidos en los campos taget y data.
data contiene un NumPy array con la longitud de pétalo y sépalo. Las filas corresponden a cada flor encontrada y las columnas con los valores

In [8]:
print("tipo de los datos:", type(iris_dataset["data"]))

tipo de los datos: <class 'numpy.ndarray'>


In [10]:
print("Forma de los datos:" , iris_dataset["data"].shape)

Forma de los datos: (150, 4)


In [11]:
print("Primeras filas de datos : " , iris_dataset["data"][:5])

Primeras filas de datos :  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [12]:
print("Datos conocidos:" , iris_dataset["target"])

Datos conocidos: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(iris_dataset["data"],iris_dataset["target"],random_state=0)

In [18]:
print("X train shape:" , x_train.shape)
print("Y train shape:" , y_train.shape)

X train shape: (112, 4)
Y train shape: (112,)


In [19]:
print("X test shape:" , x_test.shape)
print("Y test shape:" , y_test.shape)

X test shape: (38, 4)
Y test shape: (38,)


In [23]:
print("X test:" , x_test)

X test: [[5.8 2.8 5.1 2.4]
 [6.  2.2 4.  1. ]
 [5.5 4.2 1.4 0.2]
 [7.3 2.9 6.3 1.8]
 [5.  3.4 1.5 0.2]
 [6.3 3.3 6.  2.5]
 [5.  3.5 1.3 0.3]
 [6.7 3.1 4.7 1.5]
 [6.8 2.8 4.8 1.4]
 [6.1 2.8 4.  1.3]
 [6.1 2.6 5.6 1.4]
 [6.4 3.2 4.5 1.5]
 [6.1 2.8 4.7 1.2]
 [6.5 2.8 4.6 1.5]
 [6.1 2.9 4.7 1.4]
 [4.9 3.6 1.4 0.1]
 [6.  2.9 4.5 1.5]
 [5.5 2.6 4.4 1.2]
 [4.8 3.  1.4 0.3]
 [5.4 3.9 1.3 0.4]
 [5.6 2.8 4.9 2. ]
 [5.6 3.  4.5 1.5]
 [4.8 3.4 1.9 0.2]
 [4.4 2.9 1.4 0.2]
 [6.2 2.8 4.8 1.8]
 [4.6 3.6 1.  0.2]
 [5.1 3.8 1.9 0.4]
 [6.2 2.9 4.3 1.3]
 [5.  2.3 3.3 1. ]
 [5.  3.4 1.6 0.4]
 [6.4 3.1 5.5 1.8]
 [5.4 3.  4.5 1.5]
 [5.2 3.5 1.5 0.2]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.2]
 [5.2 2.7 3.9 1.4]
 [5.7 3.8 1.7 0.3]
 [6.  2.7 5.1 1.6]]


construccion del model con K nearest neightbors .  Utilizaremos k = 1 Cargamos la clase de sclkit que contiene el algoritmo

In [24]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

El algoritmo esta encapsulado en el objeto knn. Para construir el modelo con el conjunto de entrenamiento tenemos que llamar a la funcion fit que empareja datos con etiquetas

In [25]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

hacemos predicciones. Utilizamos el modelo con nuevos datos(necesitamos hacerlo bifimensional para que sclkitlearn siempre espera datos asi)

In [30]:
import numpy as np
x_new = np.array([[5,2.9,1,0.2]])
print("X new shape : " , x_new.shape)

X new shape :  (1, 4)


In [31]:
prediction = knn.predict(x_new)
print("Prediccion:" , prediction)
print("Especie predicha:" , iris_dataset["target_names"][prediction])

Prediccion: [0]
Especie predicha: ['setosa']


In [32]:
y_pred = knn.predict(x_test)
print("Predicciones para el conjunto de test:" , y_pred)

Predicciones para el conjunto de test: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [35]:
print("porcentaje en el test: {:.2f}".format(np.mean(y_pred == y_test)))
print("porcentaje en el test: {:.2f}".format(knn.score(x_test, y_test)))

porcentaje en el test: 0.97
porcentaje en el test: 0.97
